#%RAML 1.0 Library
usage: 
types: 
      x-transaction-id:
          type: string
          description: This header is returned as part of response that serves as a unique transaction id
          example: 7b404180fbb84b099179a4126f